import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const ts=createRequire(new URL('../angular-client/package.json',import.meta.url))('typescript');
const base='../angular-client/src/app/';
const signal=value=>{const f=()=>value;f.set=v=>value=v;f.update=fn=>value=fn(value);return f};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
function source(path){return readFileSync(new URL(base+path+'.ts',import.meta.url),'utf8')}
function load(path,name){const code=ts.transpileModule(source(path),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,experimentalDecorators:true}}).outputText;const exports={};const decorator=()=>()=>{};new Function('exports','require',code)(exports,n=>n==='@angular/core'?{Component:decorator,Input:decorator,Output:decorator,ViewChild:decorator,HostListener:decorator,HostBinding:decorator,ChangeDetectionStrategy:{Eager:1},signal,computed:fn=>fn,inject:()=>({})}:n==='rxjs'?{firstValueFrom:x=>x}:new Proxy({},{get:(_,key)=>key==='syncDialysisOrigin'?()=>{}:class{}}));return exports[name].prototype;}
const patients=load('features/patients/patients.component','PatientsComponent');
function searchFixture(){return Object.assign(Object.create(patients),{searchPerformed:signal(false),searchMatches:signal([]),globalSearchTerm:signal('同名'),activeTab:signal('ipd'),isPageLocked:()=>false,patientSaving:()=>false,canLeave:()=>true,patientStore:{allPatients:()=>[{id:'A',name:'同名',medicalRecordNumber:'UX-Abc',status:'opd'},{id:'B',name:'同名',medicalRecordNumber:'UX-DEF',status:'er'}]},editingPatient:signal(null),modalType:signal(''),isModalVisible:signal(false)});}
test('search matches multiple and case-insensitive MRN without opening or writing',()=>{const p=searchFixture();p.handleGlobalSearch('同名');assert.equal(p.searchMatches().length,2);assert.equal(p.isModalVisible(),false);p.handleGlobalSearch('ux-ABC');assert.deepEqual(p.searchMatches().map(x=>x.id),['A']);p.handleGlobalSearch('missing');assert.equal(p.searchMatches().length,0);assert.equal(p.isModalVisible(),false);});
test('explicit creation requires an empty result and preserves numeric MRN prefill',()=>{const p=searchFixture();p.globalSearchTerm.set('12345678');p.handleGlobalSearch('12345678');p.createFromSearch();assert.equal(p.editingPatient().medicalRecordNumber,'12345678');assert.equal(p.modalType(),'ipd');assert.equal(p.isModalVisible(),true);});
test('transfer selection captures exact identity and target, with no write before confirmation',()=>{const p=searchFixture(),calls=[];let confirm;p.showConfirm=(_,message,action)=>{confirm=action;assert.match(message,/UX-Abc/)};p.transferPatient=(...args)=>calls.push(args);p.requestSearchTransfer(p.patientStore.allPatients()[0]);assert.equal(calls.length,0);p.activeTab.set('er');confirm();assert.deepEqual(calls,[['A','ipd']]);});
test('read-only search cannot create or transfer',()=>{const p=searchFixture();p.isPageLocked=()=>true;p.showConfirm=()=>assert.fail('no confirmation/write');p.requestSearchTransfer(p.patientStore.allPatients()[0]);p.handleGlobalSearch('missing');p.createFromSearch();assert.equal(p.isModalVisible(),false);});
test('patient parent freezes submitted snapshot and blocks repeated save',async()=>{const p=searchFixture(),d=deferred();p.patientSaving=signal(false);let calls=0,submitted;p.preparePatientSave=value=>{calls++;submitted=value;return d.promise};p.showAlert=()=>{};const form={name:'submitted',patientStatus:{x:1}};const pending=p.handleSavePatient(form);form.name='later';await p.handleSavePatient(form);assert.equal(calls,1);assert.equal(submitted.name,'submitted');assert.equal(p.patientSaving(),true);d.reject(Error('offline'));await pending;assert.equal(p.patientSaving(),false);});
test('actual new-patient API failure retains parent editor and submitted MRN',async()=>{const p=searchFixture(),d=deferred();let calls=0,body;p.patientSaving=signal(false);p.patientStore={allPatients:()=>[]};p.authService={currentUser:()=>({uid:'admin',name:'合成人員'})};p.patientsApi={save:value=>{calls++;body=value;return d.promise}};p.showAlert=()=>{};p.isModalVisible.set(true);p.editingPatient.set({name:'新病人',medicalRecordNumber:'CU123'});const pending=p.handleSavePatient(p.editingPatient());await p.handleSavePatient(p.editingPatient());assert.equal(calls,1);assert.equal(body.medicalRecordNumber,'CU123');assert.equal(p.patientSaving(),true);d.reject(Error('offline'));await pending;assert.equal(p.isModalVisible(),true);assert.equal(p.editingPatient().medicalRecordNumber,'CU123');assert.equal(p.patientSaving(),false);});
const form=load('components/dialogs/patient-form-modal/patient-form-modal.component','PatientFormModalComponent');
test('patient form dirty cancellation and saving block close; clean close emits',()=>{const p=Object.assign(Object.create(form),{baseline:'{"name":"old"}',form:{name:'new'},saving:false,close:{emit(){assert.fail('dirty close')}}});global.confirm=()=>false;p.closeModal();p.saving=true;global.confirm=()=>assert.fail('busy does not ask');p.closeModal();assert.equal(p.canLeave(),false);});
const aki=load('features/aki-map/aki-map.component','AkiMapComponent');
test('AKI late success and failure cannot replace new detail or reopen closed view',async()=>{const p=Object.assign(Object.create(aki),{detailRequest:0,detail:signal(null),detailLoading:signal(false),message:signal(null)}),a=deferred(),b=deferred();p.akiApi={getPatient:id=>(id==='A'?a:b).promise};const old=p.openDetail('A'),next=p.openDetail('B');b.resolve({mrn:'B'});await next;a.reject(Error('late'));await old;assert.equal(p.detail().mrn,'B');assert.equal(p.message(),null);const c=deferred();p.akiApi.getPatient=()=>c.promise;const pending=p.openDetail('C');p.closeDetail();c.resolve({mrn:'C'});await pending;assert.equal(p.detail(),null);assert.equal(p.detailLoading(),false);});
const bed=load('features/bed-dashboard/bed-dashboard.component','BedDashboardComponent');
test('bedside old response cannot overwrite changed date before query subscription executes',async()=>{const d=deferred();const p=Object.assign(Object.create(bed),{dashboardRequest:0,bedKey:signal('bed1'),needsPin:signal(false),selectedDate:signal('2026-09-12'),selectedShift:signal('early'),isLoading:signal(false),errorMessage:signal(''),data:signal(null),lastRefreshLabel:signal(''),scheduleOverflowCheck(){},dashboardService:{getBedDashboard:()=>d.promise,hasStaffToken:()=>false}});const pending=p.loadDashboard();p.selectedDate.set('2026-09-13');d.reject(Error('old unauthenticated'));await pending;assert.equal(p.needsPin(),false);assert.equal(p.errorMessage(),'');assert.equal(p.data(),null);});
test('bedside latest background refresh completes loading left by earlier request',async()=>{const d=deferred();const p=Object.assign(Object.create(bed),{dashboardRequest:0,bedKey:signal('bed1'),needsPin:signal(false),selectedDate:signal('2026-09-12'),selectedShift:signal('early'),isLoading:signal(false),errorMessage:signal(''),data:signal(null),lastRefreshLabel:signal(''),scheduleOverflowCheck(){},dashboardService:{getBedDashboard:()=>d.promise,hasStaffToken:()=>true}});const first=p.loadDashboard();const second=p.loadDashboard(false);d.resolve({patient:'B'});await Promise.all([first,second]);assert.equal(p.isLoading(),false);assert.equal(p.data().patient,'B');});
test('alert display filter retains original groups and scopes failures to month and item',()=>{const path='features/lab-reports/lab-reports.component';const ast=ts.createSourceFile(path,source(path),ts.ScriptTarget.Latest,true);const cls=ast.statements.find(ts.isClassDeclaration);const expression=cls.members.find(m=>m.name?.getText(ast)==='visibleAlertGroups').initializer.getText(ast);const code=ts.transpileModule('const result='+expression,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const all=[{key:'K',items:[{patient:{id:'A'},analysisText:'done',suggestionText:''},{patient:{id:'B'},analysisText:'',suggestionText:''}]}];const p={alertDisplayFilter:signal('failed'),failedAlertSaves:signal([{id:'A_K_old'}]),alertResultMonthRange:'new',savedAlertSignatures:new Map([['A_K_new','["done",""]']]),groupedAlerts:()=>all};const visible=new Function('computed',code+';return result;').call(p,fn=>fn);assert.equal(visible().length,0);p.failedAlertSaves.set([{id:'A_K_new'}]);assert.equal(visible()[0].items[0].patient.id,'A');p.alertDisplayFilter.set('pending');assert.equal(visible()[0].items.length,2);assert.equal(all[0].items.length,2);p.failedAlertSaves.set([]);assert.equal(visible()[0].items[0].patient.id,'B');});
test('new templates parse and focus/anchor/keyboard contracts retain handlers',async()=>{const {parseTemplate}=await import('../angular-client/node_modules/@angular/compiler/fesm2022/compiler.mjs');const paths=['features/patients/patients.component','features/kidit-quarterly-input/kidit-quarterly-input.component','features/kidit-report/kidit-report.component','features/catastrophic-illness/catastrophic-illness.component','features/lab-reports/lab-reports.component',...['patient-form-modal','patient-detail-modal','dialysis-order-modal','lab-alert-detail-modal'].map(n=>'components/dialogs/'+n+'/'+n+'.component')];for(const p of paths){const html=readFileSync(new URL(base+p+'.html',import.meta.url),'utf8');assert.equal(parseTemplate(html,p).errors,null,p);if(p.includes('/dialogs/'))assert.match(html,/appModalFocus/);}
 const html=readFileSync(new URL(base+'features/catastrophic-illness/catastrophic-illness.component.html',import.meta.url),'utf8');const ids=[...html.matchAll(/id="(ci-[^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const match of html.matchAll(/href="#(ci-[^"]+)"/g))assert.ok(ids.includes(match[1]));
});
