import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const ts = createRequire(new URL('../angular-client/package.json', import.meta.url))('typescript');
const base = '../angular-client/src/app/';
const signal = value => { const f = () => value; f.set = v => value = v; f.update = fn => value = fn(value); return f; };
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return {promise,resolve,reject}; };
const decorator = () => () => {};
let createOrder = async () => {};
function load(path, name) {
  const source = readFileSync(new URL(base + path + '.ts', import.meta.url), 'utf8');
  const result = ts.transpileModule(source, {reportDiagnostics:true, compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,experimentalDecorators:true}});
  assert.deepEqual(result.diagnostics?.filter(d=>d.category===ts.DiagnosticCategory.Error), []);
  const exports = {};
  new Function('exports','require',result.outputText)(exports, n => n === '@angular/core' ? {Component:decorator,Input:decorator,Output:decorator,HostListener:decorator,HostBinding:decorator,ViewChild:decorator,ChangeDetectionStrategy:{Eager:1},signal,computed:fn=>fn,inject:()=>({}),EventEmitter:class{emit(){}}} : n==='rxjs' ? {firstValueFrom:v=>v} : new Proxy({}, {get:(_,key)=>key==='createDialysisOrderAndUpdatePatient' ? (...args)=>createOrder(...args) : key==='createEmptyFormData' ? ()=>({}) : class {}}));
  return exports[name].prototype;
}
const summary = load('features/patients/patient-summary/patient-summary.component','PatientSummaryComponent');
test('summary search matches mixed-case MRN using its real computed initializer',()=>{
 const path='features/patients/patient-summary/patient-summary.component';
 const source=ts.createSourceFile(path,readFileSync(new URL(base+path+'.ts',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true);
 const cls=source.statements.find(ts.isClassDeclaration);
 const expression=cls.members.find(m=>m.name?.getText(source)==='filteredPatients').initializer.getText(source);
 const code=ts.transpileModule('const result = '+expression,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const p={searchTerm:signal(' uX-aBc '),patientStore:{allPatients:()=>[{id:'A',name:'甲',medicalRecordNumber:'UX-ABC-01'},{id:'B',name:'乙',medicalRecordNumber:'OTHER'}]}};
 const result=new Function('computed',code+';return result;').call(p,fn=>fn);
 assert.deepEqual(result().map(row=>row.id),['A']);
 p.searchTerm.set('甲');assert.deepEqual(result().map(row=>row.id),['A']);
});
function summaryFixture() { return Object.assign(Object.create(summary), {requestId:0,loadError:signal(''),selectedId:signal(null),searchTerm:signal(''),loading:signal(false),datesExpanded:signal(false),patient:signal(null),dialysisDates:signal(null),orderHistory:signal([])}); }
test('summary ignores old success and old finally while next patient still loads', async()=>{
 const p=summaryFixture(),a=deferred(),b=deferred();p.api={get:url=>url.includes('/A')||url==='/orders/history'?a.promise:b.promise};
 // Distinguish order-history query by captured patient.
 p.api.get=(url,query)=> (url.includes('/A')||query?.patientId==='A'?a:b).promise;
 const old=p.selectPatient({id:'A'}),latest=p.selectPatient({id:'B'});a.resolve({id:'A'});await old;
 assert.equal(p.patient().id,'B');assert.equal(p.loading(),true);b.resolve({id:'B'});await latest;assert.equal(p.patient().id,'B');assert.equal(p.loading(),false);
});
test('summary old failure after clear does not publish errors or patient data',async()=>{const p=summaryFixture(),a=deferred();p.api={get:()=>a.promise};const old=p.selectPatient({id:'A'});p.clearSelection();a.reject(Error('old'));await old;assert.equal(p.patient(),null);assert.equal(p.loadError(),'');});
test('summary dirty child cancels both patient and subtab change',async()=>{const p=summaryFixture();p.basicProfile={canLeave:()=>false};p.subTab=signal('basic');await p.selectPatient({id:'B'});p.setSubTab('history');assert.equal(p.selectedId(),null);assert.equal(p.subTab(),'basic');});
const profile=load('features/patients/patient-basic-profile/patient-basic-profile.component','PatientBasicProfileComponent');
function profileFixture(){const p=Object.assign(Object.create(profile),{patient:{id:'A'},owner:1,baseline:'',form:signal({}),rocBirthInput:signal(''),rocBirthError:signal(false),patientSig:signal(null),saveState:signal('idle'),saveMessage:signal(''),readOnly:()=>false,patientStore:{forceRefreshPatients:async()=>{}},saved:{emit(){}}});p.form.set(p.emptyForm());p.baseline=JSON.stringify([p.form(),'']);return p;}
test('profile saves submitted snapshot without marking later edits saved',async()=>{const p=profileFixture(),d=deferred();p.api={put:()=>d.promise};p.patch('phone','first');const pending=p.save();p.patch('phone','second');d.resolve(null);await pending;assert.equal(p.form().phone,'second');assert.equal(p.hasUnsavedChanges(),true);assert.equal(p.saveState(),'idle');});
test('profile stale failure cannot mark another patient failed',async()=>{const p=profileFixture(),d=deferred();p.api={put:()=>d.promise};const pending=p.save();p.patient={id:'B'};p.owner++;p.saveState.set('idle');d.reject(Error('old'));await pending;assert.equal(p.saveState(),'idle');});
test('profile stale success never emits old patient into new view',async()=>{const p=profileFixture(),d=deferred();let emits=0;p.saved={emit(){emits++}};p.api={put:()=>d.promise};const pending=p.save();p.patient={id:'B'};p.owner++;p.form.set({...p.emptyForm(),phone:'B'});p.saveState.set('idle');d.resolve({id:'A',phone:'old'});await pending;assert.equal(p.patient.id,'B');assert.equal(p.form().phone,'B');assert.equal(emits,0);});
test('profile failed save retains editable submitted draft',async()=>{const p=profileFixture();p.patch('phone','draft');p.api={put:async()=>{throw Error('offline')}};await p.save();assert.equal(p.form().phone,'draft');assert.equal(p.hasUnsavedChanges(),true);assert.equal(p.saveState(),'error');});
const med=load('features/med-adjustment/med-adjustment.component','MedAdjustmentComponent');
function medFixture(){return Object.assign(Object.create(med),{loadOwner:0,listOwner:0,patientList:signal([{patientId:'A'},{patientId:'B'}]),selectedIndex:signal(0),isSaving:signal(false),isLoading:signal(false),isDirty:signal(false),savedHint:signal(''),dataRevision:signal(0),adjustNotes:{},savedNotes:{},akOptions:[],currentMonth:'2026-09',prefillAdjustNotes(){},initStructuredAdjustInputs(){},apiConfig:{apiBaseUrl:'',getToken:()=>''}});}
test('med load success and finally belong to captured patient',async()=>{const p=medFixture(),a=deferred(),b=deferred();for(const key of ['historyApi','medsApi','labsApi','draftsApi'])p[key]={fetchWhere:q=>(q.patientId==='A'?a:b).promise};const oldFetch=global.fetch;global.fetch=async()=>({ok:true,json:async()=>[]});try{const old=p.loadPatientData();p.selectedIndex.set(1);const next=p.loadPatientData();a.resolve([{kind:'med_adjustment',month:'2026-09',notes:{text:'A'}}]);await old;assert.equal(p.isLoading(),true);b.resolve([{kind:'med_adjustment',month:'2026-09',notes:{text:'B'}}]);await next;assert.equal(p.adjustNotes.text,'B');}finally{global.fetch=oldFetch;}});
test('med saved notes reflect submitted snapshot and keep subsequent edits dirty',async()=>{const p=medFixture(),d=deferred();p.adjustNotes={text:'submitted'};p.draftsApi={save:()=>d.promise};const pending=p.saveAdjustments();p.adjustNotes.text='later';d.resolve({});await pending;assert.equal(p.savedNotes.text,'submitted');assert.equal(p.isDirty(),true);});
test('med pending save blocks patient navigation; failed save retains original notes',async()=>{const p=medFixture(),d=deferred();p.adjustNotes={text:'draft'};p.isDirty.set(true);p.draftsApi={save:()=>d.promise};const pending=p.saveAdjustments();await p.selectPatient(1);assert.equal(p.selectedIndex(),0);assert.equal(p.canLeave(),false);d.reject(Error('offline'));await pending;assert.equal(p.adjustNotes.text,'draft');assert.equal(p.isDirty(),true);assert.equal(p.isSaving(),false);});
test('med dirty cancellation preserves patient and group',async()=>{const p=medFixture();p.isDirty.set(true);p.groupFreq='一三五';global.confirm=()=>false;await p.selectPatient(1);p.changeGroup('groupFreq','二四六');assert.equal(p.selectedIndex(),0);assert.equal(p.groupFreq,'一三五');});
const ci=load('features/catastrophic-illness/catastrophic-illness.component','CatastrophicIllnessComponent');
function ciFixture(){return Object.assign(Object.create(ci),{owner:0,selectedPatient:signal({id:'A'}),applications:signal([]),form:{notes:'draft'},baseline:'{}',formLoaded:true,currentId:null,activeTab:'initial',loading:false,saving:false,canWrite:true,statusMessage:'',loadOverview:async()=>{},loadApplications:async()=>{}});}
test('CI create is single flight, locks patient changes and retains submitted payload',async()=>{const p=ciFixture(),d=deferred();let calls=0,body;p.api={post:(_,b)=>{calls++;body=b;return d.promise}};const pending=p.save();await p.save();await p.selectPatient({id:'B'});assert.equal(p.selectedPatient().id,'A');p.form.notes='later';assert.equal(body.formData.notes,'draft');d.resolve({id:'application-A'});await pending;assert.equal(calls,1);assert.equal(p.currentId,'application-A');assert.equal(p.hasUnsavedChanges(),true);});
test('CI old create completion cannot attach old ID or clear new busy flag',async()=>{const p=ciFixture(),d=deferred();p.api={post:()=>d.promise};const pending=p.save();p.owner++;p.selectedPatient.set({id:'B'});d.resolve({id:'application-A'});await pending;assert.equal(p.currentId,null);assert.equal(p.saving,true);});
test('CI current save failure preserves form and permits retry',async()=>{const p=ciFixture();p.api={post:async()=>{throw Error('offline')}};await p.save();assert.equal(p.form.notes,'draft');assert.equal(p.saving,false);assert.equal(p.hasUnsavedChanges(),true);});
test('CI old application-list response cannot replace new patient list',async()=>{const p=ciFixture(),d=deferred();p.api={get:()=>d.promise};const pending=ci.loadApplications.call(p);p.owner++;p.applications.set([{id:'new'}]);d.resolve([{id:'old'}]);await pending;assert.equal(p.applications()[0].id,'new');});
const patients=load('features/patients/patients.component','PatientsComponent');
test('dialysis order repeated save sends one request and write failure keeps modal draft',async()=>{const d=deferred();let calls=0;createOrder=()=>{calls++;return d.promise};const p={orderSaving:signal(false),isPageLocked:()=>false,editingPatientForOrder:()=>({id:'A',name:'A'}),isOrderModalVisible:signal(true),showAlert(){},patientStore:{forceRefreshPatients:async()=>{}},recalculateStatsLocally:async()=>{},notificationService:{createNotification(){}}};const old=patients.handleSaveOrder.call(p,{mode:'HD'});await patients.handleSaveOrder.call(p,{mode:'HD'});assert.equal(calls,1);d.reject(Error('offline'));await old;assert.equal(p.isOrderModalVisible(),true);assert.equal(p.orderSaving(),false);});
test('dialysis successful write with failed refresh closes form to prevent duplicate recreation',async()=>{createOrder=async()=>{};const p={orderSaving:signal(false),isPageLocked:()=>false,editingPatientForOrder:()=>({id:'A'}),isOrderModalVisible:signal(true),showAlert(){},patientStore:{forceRefreshPatients:async()=>{throw Error('refresh')}},recalculateStatsLocally:async()=>{},notificationService:{createNotification(){}}};await patients.handleSaveOrder.call(p,{});assert.equal(p.isOrderModalVisible(),false);assert.equal(p.orderSaving(),false);});
test('dialysis refresh failure retains one accurate visible completion message',async()=>{createOrder=async()=>{};const alerts=[];const p={orderSaving:signal(false),isPageLocked:()=>false,editingPatientForOrder:()=>({id:'A',name:'A'}),isOrderModalVisible:signal(true),showAlert:(...args)=>alerts.push(args),patientStore:{forceRefreshPatients:async()=>{throw Error('refresh')}},recalculateStatsLocally:async()=>{},notificationService:{createNotification(){}}};await patients.handleSaveOrder.call(p,{});assert.equal(alerts.length,1);assert.equal(alerts[0][0],'醫囑已儲存');assert.match(alerts[0][1],/刷新失敗/);assert.match(alerts[0][1],/不需再提交/);assert.equal(p.isOrderModalVisible(),false);});
test('physician hub cancelled child leave keeps tab and URL',()=>{const proto=load('features/physician-hub/physician-hub.component','PhysicianHubComponent');const p=Object.assign(Object.create(proto),{mainTab:signal('med'),tabs:()=>[{key:'ci'}],med:{canLeave:()=>false},router:{navigate(){assert.fail('must not navigate')}}});p.setTab('ci');assert.equal(p.mainTab(),'med');});
test('cancelled native selectors display the retained patient and group',()=>{const p=medFixture();p.isDirty.set(true);p.groupFreq='一三五';global.confirm=()=>false;const patient={value:'1'},group={value:'二四六'};p.onSelectChange('1',patient);p.changeGroup('groupFreq','二四六',group);assert.equal(patient.value,'0');assert.equal(group.value,'一三五');});
test('CI stale source failures and selection finally do not clear new loading or sources',async()=>{const p=ciFixture();p.formLoaded=false;p.loadApplications=ci.loadApplications;p.loadLatestLabs=ci.loadLatestLabs;p.loadKiditProfile=ci.loadKiditProfile;const a=deferred(),b=deferred();p.api={get:(url,q)=>(url.endsWith('/A')||q?.patientId==='A'?a:b).promise};p.labsApi={fetchWhere:q=>(q.patientId==='A'?a:b).promise};const old=p.selectPatient({id:'A'}),next=p.selectPatient({id:'B'});a.reject(Error('old'));await old;assert.equal(p.loading,true);assert.equal(p.statusMessage,'');b.resolve([]);await next;assert.equal(p.loading,false);assert.equal(p.selectedPatient().id,'B');});
test('owned templates parse and added handlers resolve on component classes',async()=>{
 const {parseTemplate}=await import('../angular-client/node_modules/@angular/compiler/fesm2022/compiler.mjs');
 for(const path of ['features/patients/patient-summary/patient-summary.component','features/patients/patient-basic-profile/patient-basic-profile.component','features/med-adjustment/med-adjustment.component','features/catastrophic-illness/catastrophic-illness.component','features/physician-hub/physician-hub.component','features/patients/patients.component','components/dialogs/dialysis-order-modal/dialysis-order-modal.component']){
  const html=readFileSync(new URL(base+path+'.html',import.meta.url),'utf8');assert.deepEqual(parseTemplate(html,path).errors,null,path);
  const source=ts.createSourceFile(path,readFileSync(new URL(base+path+'.ts',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true);
  const cls=source.statements.find(ts.isClassDeclaration),names=new Set(cls.members.map(m=>m.name?.getText(source)));
  for(const name of ['setSubTab','changeGroup','onSelectChange','closeOrderModal','orderSaving','saving'])if(html.includes(name+'(')||html.includes('="'+name+'"'))assert.ok(names.has(name),path+': '+name);
 }
});
test('all clinical aliases and weekly/stats keep route leave protection',()=>{const source=readFileSync(new URL(base+'app.routes.ts',import.meta.url),'utf8');for(const route of ['patients','weekly','stats','physician','physician-schedule','orders','med-adjustment','catastrophic-illness','research']){assert.match(source,new RegExp("path: '"+route+"',\\s*canDeactivate: \\[manualEditorGuard\\]"));}});
test('shared actual dialysis writer rejects all same-patient reentry, allows other patients and releases after failure',async()=>{
 const source=readFileSync(new URL('../angular-client/src/services/optimizedApiService.ts',import.meta.url),'utf8');
 const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 const exports={},a=deferred();const writes=[];
 new Function('exports','require',code)(exports,n=>n.includes('localApiClient')?{__esModule:true,default:()=>({save:body=>{writes.push(body);return body.patientId==='A'?a.promise:Promise.resolve()}}),localApi:{}}:{getNowISO:()=> '2026-09-12T10:00:00',formatDateToYYYYMMDD:()=> '2026-09-12'});
 const save=exports.createDialysisOrderAndUpdatePatient;const pending=save('A','甲',{mode:'HD'});
 await assert.rejects(save('A','甲',{mode:'HD'}),/尚未提交/);await assert.rejects(save('A','甲',{mode:'HDF'}),/尚未提交/);
 await save('B','乙',{mode:'HD'});assert.equal(writes.length,2);a.reject(Error('offline'));await assert.rejects(pending,/offline/);
 // Reentry after settled failure reaches HTTP again rather than remaining locked.
 await assert.rejects(save('A','甲',{mode:'HD'}),/offline/);assert.equal(writes.length,3);
});
const myPatients=load('features/my-patients/my-patients.component','MyPatientsComponent');
test('my-patients save locks both entry points and closing, and failure preserves patient',async()=>{const d=deferred();let calls=0;createOrder=()=>{calls++;return d.promise};const p=Object.assign(Object.create(myPatients),{orderSaving:signal(false),selectedPatientForOrder:signal({id:'A',name:'甲'}),isOrderModalVisible:signal(true),notificationService:{createNotification(){}},patientStore:{allPatients:()=>[{id:'B'}]}});const pending=p.handleOrderSave({mode:'HD'});p.closeOrderModal();p.openOrderModal({patientId:'B'});p.openOrderModalFromIcu({id:'B'});await p.handleOrderSave({mode:'HDF'});assert.equal(calls,1);assert.equal(p.selectedPatientForOrder().id,'A');assert.equal(p.isOrderModalVisible(),true);d.reject(Error('offline'));await pending;assert.equal(p.orderSaving(),false);assert.equal(p.selectedPatientForOrder().id,'A');});
test('PD successful creation selects created patient despite external busy guard',async()=>{const p=ciFixture(),d=deferred();Object.assign(p,{pdOwner:0,pdSaving:false,pdForm:{name:'PD'},pdDialogTarget:'select',pdDialogOpen:true,pdPatients:[],formLoaded:false,toPdPatient:x=>x});p.loadLatestLabs=async()=>{};p.loadKiditProfile=async()=>{};let calls=0;p.api={post:()=>{calls++;return d.promise}};const pending=p.savePdPatient();p.closePdDialog();await p.savePdPatient();assert.equal(p.pdDialogOpen,true);assert.equal(calls,1);d.resolve({id:'PD-1'});await pending;assert.equal(p.selectedPatient().id,'PD-1');assert.equal(p.pdSaving,false);});
test('expiry combined write keeps original snapshot and later draft while saving',async()=>{const p=ciFixture(),d=deferred(),posts=[];Object.assign(p,{expiryOwner:0,expiryPickedPatient:{id:'A'},newExpiryDate:'2027-01-01',newSentDate:'2026-09-12',newExpiryPhysician:'甲醫師',addingExpiry:false,overviewRows:()=>[]});p.api={put:()=>d.promise,post:(_,b)=>{posts.push(b);return Promise.resolve()}};const pending=p.addExpiry();p.pickExpiryPatient({id:'B'});assert.equal(p.expiryPickedPatient.id,'A');p.newSentDate='2026-10-01';p.newExpiryPhysician='乙醫師';d.resolve({});await pending;assert.equal(posts[0].clerkSentDate,'2026-09-12');assert.equal(posts[0].physicianName,'甲醫師');assert.equal(p.newSentDate,'2026-10-01');assert.equal(p.newExpiryPhysician,'乙醫師');});
test('PD failure retains the form and re-enables retry',async()=>{const p=ciFixture();Object.assign(p,{pdOwner:0,pdSaving:false,pdForm:{name:'PD 草稿'},pdDialogTarget:'select',pdDialogOpen:true,pdPatients:[]});p.api={post:async()=>{throw Error('offline')}};await p.savePdPatient();assert.equal(p.pdDialogOpen,true);assert.equal(p.pdForm.name,'PD 草稿');assert.equal(p.pdSaving,false);});
test('expiry pending double submit writes once and failure retains selected draft',async()=>{const p=ciFixture(),d=deferred();let calls=0;global.alert=()=>{};Object.assign(p,{expiryOwner:0,expiryPickedPatient:{id:'A'},newExpiryDate:'2027-01-01',newSentDate:'',newExpiryPhysician:'醫師',addingExpiry:false,overviewRows:()=>[]});p.api={put:()=>{calls++;return d.promise}};const pending=p.addExpiry();await p.addExpiry();assert.equal(calls,1);d.reject(Error('offline'));await pending;assert.equal(p.expiryPickedPatient.id,'A');assert.equal(p.newExpiryDate,'2027-01-01');assert.equal(p.addingExpiry,false);});
test('all four live dialysis modal callers bind their parent saving state',()=>{for(const feature of ['patients','my-patients','schedule','stats']){const html=readFileSync(new URL(base+`features/${feature}/${feature}.component.html`,import.meta.url),'utf8');const modal=html.match(/<app-dialysis-order-modal\b[^>]*>/)?.[0];assert.ok(modal,feature);assert.match(modal,/\[saving\]="orderSaving(?:\(\))?"/,feature);assert.match(modal,/\(close\)="closeOrderModal\(\)"/,feature);}});
test('hub delegates schedule leave once without a second fallback confirmation',()=>{const proto=load('features/physician-hub/physician-hub.component','PhysicianHubComponent');let calls=0;const p=Object.assign(Object.create(proto),{mainTab:signal('schedule'),schedule:{canLeave(){calls++;return true;},isLoading(){assert.fail('no fallback')},hasUnsavedChanges(){assert.fail('no fallback')}}});assert.equal(p.canLeave(),true);assert.equal(calls,1);});
