import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';
const ts=createRequire(new URL('../angular-client/package.json',import.meta.url))('typescript');
const code=ts.transpileModule(readFileSync(new URL('../angular-client/src/app/features/inventory/inventory.component.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,experimentalDecorators:true}}).outputText;
const signal=v=>{const f=()=>v;f.set=x=>v=x;f.update=g=>v=g(v);return f;};const storage=new Map();globalThis.sessionStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};const exports={};new Function('exports','require',code)(exports,n=>n==='@angular/core'?{ChangeDetectionStrategy:{OnPush:0,Eager:1,Default:1},Component:()=>x=>x,HostListener:()=>()=>{},ViewChild:()=>()=>{},signal,computed:f=>f}:n==='rxjs'?{firstValueFrom:async v=>v}:{});
function fixture(){const p=Object.create(exports.InventoryComponent.prototype);Object.assign(p,{authService:{currentUser:()=>({id:'verifier-user'})},countDraftInfo:signal(''),categoryKeys:['artificialKidney','dialysateCa','bicarbonateType'],countBoxes:{artificialKidney:{A:1},dialysateCa:{},bicarbonateType:{}},countLoose:{artificialKidney:{},dialysateCa:{},bicarbonateType:{}},countUnits:{artificialKidney:{},dialysateCa:{},bicarbonateType:{}},countFilter:{date:'2026-09-01'},countOwnerDate:'2026-09-01',countNotes:'before',countCutoff:'end-of-day',countType:'weekly',countRevision:1,countRequest:0,countsSaving:signal(false),countsLoading:signal(false),countDocExists:signal(true),countDocInfo:signal(null),dashboardLoaded:signal(true),weeklyDataLoaded:signal(true),getUnitsPerBox:()=>1,loadCountRecords:async()=>{},showAlert:()=>{},});p.countSnapshot=p.draftSnapshot();return p;}
test('count response does not mark later edits clean',async()=>{const p=fixture();let resolve;p.countsApi={save:()=>new Promise(r=>resolve=r)};const saving=p.saveCountDoc();p.countNotes='later edit';resolve({revision:2});await saving;assert.equal(p.hasUnsavedChanges(),true);assert.equal(p.countRevision,2);});
test('count response cannot assign saved date revision to newly selected date',async()=>{const p=fixture();let resolve;p.countsApi={save:()=>new Promise(r=>resolve=r)};const saving=p.saveCountDoc();p.countOwnerDate='2026-09-02';p.countFilter.date='2026-09-02';p.countRevision=9;resolve({revision:2});await saving;assert.equal(p.countRevision,9);});
test('delete refreshes tombstone for same-date recreation',async()=>{const p=fixture();p.api={delete:async()=>({}),get:()=>Promise.reject({status:404,error:{revision:2}})};const previous=globalThis.confirm;globalThis.confirm=()=>true;try{await p.deleteCountDoc();assert.equal(p.countRevision,2);assert.equal(p.hasUnsavedChanges(),false);}finally{globalThis.confirm=previous;}});test('monthly unknown forecast is not displayed as zero consumption',async()=>{const p=fixture();Object.assign(p,{countReportLoading:signal(false),countReportLoaded:signal(false),countReportRows:signal([]),countReportFilter:{month:'2026-09'},countReportBaseDate:signal(''),countReportLastCountDate:signal(''),countReportNote:signal(''),countsApi:{fetchAll:async()=>[]},purchasesApi:{fetchAll:async()=>[]},getItemsForCategory:c=>c==='artificialKidney'?['A']:[],stock:{monthRange:()=>({start:'2026-09-01',end:'2026-09-30'}),arrivedBetween:()=>({}),consumptionBetween:async()=>({grouped:{},warnings:['artificialKidney 2026-09-01/2026-09-30：排程推估載入失敗，數量未知'],categorySources:{artificialKidney:{actualDays:0,estimatedDays:30}}}),addDays:()=> '2026-08-31',itemTimeline:async()=>({current:10}),value:(g,c,i)=>g?.[c]?.[i]||0,daysLabel:()=>''}});await p.loadCountMonthReport();assert.equal(p.countReportRows()[0].consumed,null);});test('draft belongs to date and user, stale base revision stays conflicting',()=>{const p=fixture();p.saveCountDraft();p.countNotes='cleared';p.countRevision=2;p.restoreCountDraft();assert.equal(p.countNotes,'before');assert.equal(p.countRevision,1);assert.match(p.countDraftInfo(),/版本不同/);const q=fixture();q.authService={currentUser:()=>({id:'other'})};q.restoreCountDraft();assert.match(q.countDraftInfo(),/尚無草稿/);p.countOwnerDate='2026-09-02';p.restoreCountDraft();assert.match(p.countDraftInfo(),/尚無草稿/);});
test('uncertain order retry sends identical captured payload without duplicate precheck',async()=>{const p=fixture();let calls=0;const sent=[];Object.assign(p,{orderRetryPayload:[{item:'A',quantity:3}],orderIdempotencyKey:'same-key',orderCreated:signal(false),purchasesApi:{fetchAll:async()=>{throw Error('must bypass precheck')}},fetchPurchases:async()=>{},api:{post:(_path,body)=>{sent.push(JSON.stringify(body));return ++calls===1?Promise.reject(Error('response lost')):Promise.resolve({count:1});}}});await p.createCalendarOrdersFromPreview();assert.ok(p.orderRetryPayload);await p.createCalendarOrdersFromPreview();assert.equal(calls,2);assert.equal(sent[0],sent[1]);assert.equal(p.orderCreated(),true);assert.equal(p.orderRetryPayload,null);});test('same-name different-category modal keeps newest response',async()=>{const p=fixture();const pending={};Object.assign(p,{itemDetailRequest:0,selectedStockItem:signal(null),itemDetail:signal(null),itemDetailPurchases:signal([]),itemDetailLoading:signal(false),countsApi:{fetchAll:async()=>[]},purchasesApi:{fetchAll:async()=>[]},stock:{todayString:()=> '2026-09-12',addDays:()=> '2026-09-25',enumerateDays:()=>[],itemTimeline:c=>new Promise(r=>pending[c]=r)}});const previous=globalThis.document;globalThis.document={activeElement:{focus:()=>{}},getElementById:()=>null};try{const a=p.openStockItem('artificialKidney','Same');await Promise.resolve();await Promise.resolve();const b=p.openStockItem('dialysateCa','Same');await Promise.resolve();await Promise.resolve();pending.dialysateCa({current:22});await b;pending.artificialKidney({current:11});await a;assert.equal(p.itemDetail().current,22);assert.equal(p.itemDetailLoading(),false);await new Promise(r=>setTimeout(r,10));}finally{globalThis.document=previous;}});
function overviewFixture(timeline, unknownToday=false){
  const p=fixture();Object.assign(p,{
    dashboardLoading:signal(false),forecastLoading:signal(false),dashboardHasCount:signal(false),dashboardLastCountDate:signal(''),dashboardConsumptionNote:signal(''),forecastWarnings:signal([]),todayForecast:signal({}),tomorrowForecast:signal({}),dashboardItems:signal([]),inventoryItems:()=>[],
    countsApi:{fetchAll:async()=>[{countDate:'2026-09-12'}]},purchasesApi:{fetchAll:async()=>[]},getItemsForCategory:c=>c==='artificialKidney'?['APS21S']:[],
    consumptionEngine:{calculateTheoreticalConsumption:async()=>({grouped:{},unknownCategories:unknownToday?['artificialKidney']:[],warnings:[]})},
    stock:{invalidateActualRanges:()=>{},todayString:()=> '2026-09-12',lastCompleteWeekMonday:()=> '2026-09-07',weeklyConsumption:async()=>({grouped:{},warnings:[]}),addDays:()=> '2026-09-21',itemTimeline:async()=>timeline,value:(g,c,i)=>g?.[c]?.[i]||0,safetyStock:()=>0,dailyAverage:()=>0,pendingArrivals:()=>({})}
  });return p;
}
test('known count and zero historical usage cannot claim safe when future demand is unknown',async()=>{
  const p=overviewFixture({current:200,anchor:{countDate:'2026-09-12'},days:[{date:'2026-09-13',need:null,projectedBalance:null}],firstDeficitDate:null,nextDelivery:null});
  await p.loadDashboard();assert.equal(p.dashboardItems()[0].estimatedStock,200);assert.equal(p.dashboardItems()[0].safeLevel,0);assert.equal(p.dashboardItems()[0].status,'warning');assert.equal(p.dashboardItems()[0].statusLabel,'後續需求待核對');
});
test('unknown today demand prevents safe status even if future projection is known',async()=>{
  const p=overviewFixture({current:200,days:[{need:0,projectedBalance:200}],firstDeficitDate:null},true);await p.loadDashboard();assert.equal(p.dashboardItems()[0].statusLabel,'後續需求待核對');assert.equal(p.dashboardItems()[0].todayConsumption,null);
});
test('known deficit warning takes priority over unknown later demand',async()=>{
  const p=overviewFixture({current:-1,days:[{need:null,projectedBalance:null}],firstDeficitDate:'2026-09-12'},true);await p.loadDashboard();assert.equal(p.dashboardItems()[0].status,'critical');assert.equal(p.dashboardItems()[0].statusLabel,'預計不足');
  const q=overviewFixture({current:200,days:[{need:null,projectedBalance:null}],firstDeficitDate:'2026-09-14'},true);await q.loadDashboard();assert.equal(q.dashboardItems()[0].status,'danger');assert.match(q.dashboardItems()[0].statusLabel,/2026-09-14/);
});
test('forecast empty-state does not treat missing or unknown categories as zero',()=>{const p=fixture();assert.equal(p.isForecastEmpty({artificialKidney:{},dialysateCa:{},bicarbonateType:{}}),true);assert.equal(p.isForecastEmpty({artificialKidney:{},dialysateCa:{}}),false);assert.equal(p.isForecastEmpty({artificialKidney:{A:null},dialysateCa:{},bicarbonateType:{}}),false);});
test('inventory templates have no missing implicit receiver call targets',()=>{
  const nonExpressions=new Set(['if','for','switch','Number','button','of','Modal','var','autofocus']);
  for(const name of ['inventory','purchase-calendar','inventory-item-detail']){
    const path='../angular-client/src/app/features/inventory/'+name+'.component';
    const source=ts.createSourceFile(name,readFileSync(new URL(path+'.ts',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true);
    const declaration=source.statements.find(ts.isClassDeclaration);const names=new Set(declaration.members.map(member=>member.name?.getText(source)));
    const html=readFileSync(new URL(path+'.html',import.meta.url),'utf8');const calls=[...html.matchAll(/(?<![\w$.])([A-Za-z_$][\w$]*)\s*\(/g)].map(match=>match[1]);
    assert.deepEqual([...new Set(calls)].filter(name=>!names.has(name)&&!nonExpressions.has(name)),[],name+' missing template call target');
  }
});
test('calendar applies new item/date inputs after it is already mounted',()=>{
  const calendarCode=ts.transpileModule(readFileSync(new URL('../angular-client/src/app/features/inventory/purchase-calendar.component.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,experimentalDecorators:true}}).outputText;
  const out={};new Function('exports','require',calendarCode)(out,n=>n==='@angular/core'?{ChangeDetectionStrategy:{OnPush:0,Eager:1,Default:1},Component:()=>x=>x,Input:()=>()=>{},Output:()=>()=>{},signal,computed:f=>f}:{});
  const p=Object.create(out.PurchaseCalendarComponent.prototype);let loads=0;Object.assign(p,{initialCategory:'artificialKidney',initialItem:'APS21S',initialDate:'2026-09-12',today:'2026-09-12',filterCategory:signal(''),filterItem:signal(''),selectedDate:signal('2026-09-01'),month:signal('2026-09'),loadDailyDetail:()=>{loads++;}});
  p.ngOnChanges({initialCategory:{firstChange:true},initialItem:{firstChange:true}});assert.equal(loads,0);
  p.ngOnChanges({initialCategory:{firstChange:false},initialItem:{firstChange:false},initialDate:{firstChange:false}});assert.equal(p.filterCategory(),'artificialKidney');assert.equal(p.filterItem(),'APS21S');assert.equal(p.selectedDate(),'2026-09-12');assert.equal(loads,1);
  p.initialItem='';p.initialCategory='dialysateCa';p.initialDate='2026-08-31';p.ngOnChanges({initialCategory:{firstChange:false},initialItem:{firstChange:false},initialDate:{firstChange:false}});assert.equal(p.filterItem(),'');assert.equal(p.selectedDate(),'2026-08-31');assert.equal(p.month(),'2026-08');assert.equal(loads,2);
});
