// KiDit HD處方「透析器型號」官方對照表（來源：Kidit資料匯入格式說明.xls「AK 透析器型號對應」sheet，401 筆）
// 匯出時透析器型號欄依格式說明填入「對應代碼」；本檔為產生檔，勿手改（重產腳本見 scratchpad gen-ak-map.cjs 之說明）
export interface AkDialyzerEntry {
  brand: string;
  name: string;
  code: string;
}

export const AK_DIALYZER_LIST: AkDialyzerEntry[] = [
  { brand: 'Asahi', name: 'Rexeed-13L', code: '35' },
  { brand: 'Asahi', name: 'Rexeed-15L', code: '36' },
  { brand: 'Asahi', name: 'Rexeed-18L', code: '37' },
  { brand: 'Asahi', name: 'Rexeed-21L', code: '38' },
  { brand: 'Asahi', name: 'Rexeed-13GL', code: '39' },
  { brand: 'Asahi', name: 'Rexeed-15GL', code: '40' },
  { brand: 'Asahi', name: 'Rexeed-18GL', code: '41' },
  { brand: 'Asahi', name: 'Rexeed-21GL', code: '42' },
  { brand: 'Asahi', name: 'APS-13U', code: '43' },
  { brand: 'Asahi', name: 'APS-15U', code: '44' },
  { brand: 'Asahi', name: 'APS-18U', code: '45' },
  { brand: 'Asahi', name: 'APS-21U', code: '46' },
  { brand: 'Asahi', name: 'APS-13R', code: '47' },
  { brand: 'Asahi', name: 'APS-15R', code: '48' },
  { brand: 'Asahi', name: 'APS-18R', code: '49' },
  { brand: 'Asahi', name: 'APS-21R', code: '50' },
  { brand: 'Asahi', name: 'APS-15MD', code: '51' },
  { brand: 'Asahi', name: 'APS-18MD', code: '52' },
  { brand: 'Asahi', name: 'APS-21MD', code: '53' },
  { brand: 'Asahi', name: 'APS-11S', code: '54' },
  { brand: 'Asahi', name: 'APS-13S', code: '55' },
  { brand: 'Asahi', name: 'APS-15S', code: '56' },
  { brand: 'Asahi', name: 'APS-18S', code: '57' },
  { brand: 'Asahi', name: 'APS-21S', code: '58' },
  { brand: 'Asahi', name: 'Rexeed-13A', code: '59' },
  { brand: 'Asahi', name: 'Rexeed-15A', code: '60' },
  { brand: 'Asahi', name: 'Rexeed-18A', code: '61' },
  { brand: 'Asahi', name: 'Rexeed-21A', code: '62' },
  { brand: 'Asahi', name: 'Rexeed-25A', code: '63' },
  { brand: 'Asahi', name: 'Rexeed-15GL', code: '181' },
  { brand: 'B.Braun', name: 'LO PS10', code: '69' },
  { brand: 'B.Braun', name: 'LO PS12', code: '70' },
  { brand: 'B.Braun', name: 'LO PS15', code: '71' },
  { brand: 'B.Braun', name: 'LO PS18', code: '72' },
  { brand: 'B.Braun', name: 'LO PS20', code: '73' },
  { brand: 'B.Braun', name: 'HI PS10', code: '74' },
  { brand: 'B.Braun', name: 'HI PS12', code: '75' },
  { brand: 'B.Braun', name: 'HI PS15', code: '76' },
  { brand: 'B.Braun', name: 'HI PS18', code: '77' },
  { brand: 'B.Braun', name: 'HI PS20', code: '78' },
  { brand: 'Baxter', name: 'Dicea 110G', code: '64' },
  { brand: 'Baxter', name: 'Dicea 130G', code: '65' },
  { brand: 'Baxter', name: 'Dicea 150G', code: '66' },
  { brand: 'Baxter', name: 'Dicea 170G', code: '67' },
  { brand: 'Baxter', name: 'Dicea 210G', code: '68' },
  { brand: 'FASFLO', name: '15H', code: '32' },
  { brand: 'FASFLO', name: '18H', code: '33' },
  { brand: 'FASFLO', name: '21H', code: '34' },
  { brand: 'FASFLO', name: 'PS-18H', code: '165' },
  { brand: 'FASFLO', name: 'PS-15H', code: '166' },
  { brand: 'FASFLO', name: 'PS-21H', code: '169' },
  { brand: 'Fresenius', name: 'F6HPS', code: '79' },
  { brand: 'Fresenius', name: 'F7HPS', code: '80' },
  { brand: 'Fresenius', name: 'F8HPS', code: '81' },
  { brand: 'Fresenius', name: 'F10HPS', code: '82' },
  { brand: 'Fresenius', name: 'HF60LS', code: '83' },
  { brand: 'Fresenius', name: 'HF80LS', code: '84' },
  { brand: 'Fresenius', name: 'F60S', code: '85' },
  { brand: 'Fresenius', name: 'F70S', code: '86' },
  { brand: 'Fresenius', name: 'HF80S', code: '87' },
  { brand: 'Fresenius', name: 'HF80', code: '88' },
  { brand: 'Fresenius', name: 'HdF100S', code: '89' },
  { brand: 'Fresenius', name: 'FX60', code: '90' },
  { brand: 'Fresenius', name: 'FX80', code: '91' },
  { brand: 'Fresenius', name: 'FX100', code: '92' },
  { brand: 'Fresenius', name: 'F160NR', code: '93' },
  { brand: 'Fresenius', name: 'F180NR', code: '94' },
  { brand: 'Fresenius', name: 'F200NR', code: '95' },
  { brand: 'Fresenius', name: 'FX80M', code: '152' },
  { brand: 'Fresenius', name: 'FX60M', code: '155' },
  { brand: 'Fresenius', name: 'Optiflux-F160NRe', code: '184' },
  { brand: 'Fresenius', name: 'Optiflux-F180NRe', code: '185' },
  { brand: 'Fresenius', name: 'Optiflux-F200NRe', code: '186' },
  { brand: 'Fresenius', name: 'FX60classix', code: '197' },
  { brand: 'Fresenius', name: 'FX80classix', code: '198' },
  { brand: 'Fresenius', name: 'FX100classix', code: '199' },
  { brand: 'Fresenius', name: 'FX120', code: '208' },
  { brand: 'Gambro', name: 'GPF-14L', code: '96' },
  { brand: 'Gambro', name: 'GPF-17L', code: '97' },
  { brand: 'Gambro', name: 'GPF-21L(300ml/min)', code: '98' },
  { brand: 'Gambro', name: 'GPF-140H', code: '99' },
  { brand: 'Gambro', name: 'GPF-170H', code: '100' },
  { brand: 'Gambro', name: 'GPF-210H(300ml/min)', code: '101' },
  { brand: 'Gambro', name: 'GPF-17S', code: '102' },
  { brand: 'Gambro', name: 'GPF-21S', code: '103' },
  { brand: 'Gambro', name: 'GPF-24S', code: '104' },
  { brand: 'Gambro', name: 'GPF-17R', code: '105' },
  { brand: 'Gambro', name: 'GPF-21R(300ml/min)', code: '106' },
  { brand: 'Gambro', name: 'GPF-24R(300ml/min)', code: '107' },
  { brand: 'Gambro', name: 'Tpolyflux-17L', code: '162' },
  { brand: 'Gambro', name: 'POLYFLUX-17L', code: '163' },
  { brand: 'Gambro', name: 'POLYFLUX-21L', code: '171' },
  { brand: 'Gambro', name: 'SF-150G', code: '174' },
  { brand: 'Gambro', name: 'POLYFLUX-24R', code: '187' },
  { brand: 'Gambro', name: 'POLYFLUX-21R', code: '188' },
  { brand: 'Gambro', name: 'SHM-DLPES 1.6HF', code: '190' },
  { brand: 'Gambro', name: 'SHM-DLPES 1.8HF', code: '191' },
  { brand: 'Gambro', name: 'SHM-DLPES 2.0HF', code: '192' },
  { brand: 'Gambro', name: 'SHM-DLPES 2.2HF', code: '193' },
  { brand: 'Gambro', name: 'SHM-DLPES 1.4MF', code: '203' },
  { brand: 'Gambro', name: 'SHM-DLPES 1.6MF', code: '204' },
  { brand: 'Gambro', name: 'SHM-DLPES 1.8MF', code: '205' },
  { brand: 'Gambro', name: 'SHM-DLPES 2.0MF', code: '206' },
  { brand: 'Gambro', name: 'SHM-DLPES 2.2MF', code: '207' },
  { brand: 'Gambro', name: 'PES-1.4MF', code: '210' },
  { brand: 'Gambro', name: 'PES-1.6MF', code: '211' },
  { brand: 'Gambro', name: 'PES-1.8MF', code: '212' },
  { brand: 'Hospitech', name: 'PES-1.4MF', code: '215' },
  { brand: 'Hospitech', name: 'PES-1.6MF', code: '216' },
  { brand: 'Hospitech', name: 'PES-1.8MF', code: '217' },
  { brand: 'Hospitech', name: 'PES-1.4HF', code: '226' },
  { brand: 'Hospitech', name: 'PES-1.6HF', code: '227' },
  { brand: 'Hospitech', name: 'PES-1.8HF', code: '228' },
  { brand: 'KAWASUMI', name: 'CTA-1200', code: '108' },
  { brand: 'KAWASUMI', name: 'CTA-1500', code: '109' },
  { brand: 'KAWASUMI', name: 'CTA-2000', code: '110' },
  { brand: 'KAWASUMI', name: 'PS-1300H', code: '111' },
  { brand: 'KAWASUMI', name: 'PS-1500H', code: '112' },
  { brand: 'KAWASUMI', name: 'PS-1800H', code: '113' },
  { brand: 'KAWASUMI', name: 'PS-2100H', code: '114' },
  { brand: 'KAWASUMI', name: 'PS-1500L', code: '167' },
  { brand: 'KAWASUMI', name: 'PS-2100L', code: '168' },
  { brand: 'KAWASUMI', name: 'PS-1800L', code: '170' },
  { brand: 'KAWASUMI', name: 'KF-18C', code: '172' },
  { brand: 'KAWASUMI', name: 'KF-20C', code: '173' },
  { brand: 'KURARAY', name: 'KF-12C', code: '115' },
  { brand: 'KURARAY', name: 'KF-15C', code: '116' },
  { brand: 'KURARAY', name: 'KF-18C', code: '117' },
  { brand: 'KURARAY', name: 'KF-20C', code: '118' },
  { brand: 'Nikkiso', name: 'FLX-15GW', code: '119' },
  { brand: 'Nikkiso', name: 'FLX-18GW', code: '120' },
  { brand: 'Nikkiso', name: 'FLX-21GW', code: '121' },
  { brand: 'Nikkiso', name: 'FDX-15GW', code: '122' },
  { brand: 'Nikkiso', name: 'FDX-18GW', code: '123' },
  { brand: 'Nikkiso', name: 'FDX-21GW', code: '124' },
  { brand: 'Nikkiso', name: 'FDY-180GW', code: '151' },
  { brand: 'Nikkiso', name: 'FDY-150GW', code: '180' },
  { brand: 'Nikkiso', name: 'KF-M15', code: '189' },
  { brand: 'Nikkiso', name: 'FDX-210GW', code: '209' },
  { brand: 'Nikkiso', name: 'FDY-210GW', code: '218' },
  { brand: 'Nipro', name: 'DICEA130', code: '1' },
  { brand: 'Nipro', name: 'DICEA170', code: '2' },
  { brand: 'Nipro', name: 'FX60', code: '3' },
  { brand: 'Nipro', name: 'FB130A', code: '4' },
  { brand: 'Nipro', name: 'FB150A', code: '5' },
  { brand: 'Nipro', name: 'FB170A', code: '6' },
  { brand: 'Nipro', name: 'FB210A', code: '7' },
  { brand: 'Nipro', name: 'SUREFLUX-130G', code: '8' },
  { brand: 'Nipro', name: 'SUREFLUX-150G', code: '9' },
  { brand: 'Nipro', name: 'SUREFLUX-170G', code: '10' },
  { brand: 'Nipro', name: 'SUREFLUX-190G', code: '11' },
  { brand: 'Nipro', name: 'SUREFLUX-210G', code: '12' },
  { brand: 'Nipro', name: 'FB170U', code: '13' },
  { brand: 'Nipro', name: 'FB210U', code: '14' },
  { brand: 'Nipro', name: 'PES-110DS', code: '15' },
  { brand: 'Nipro', name: 'PES-130DS', code: '16' },
  { brand: 'Nipro', name: 'PES-150DS', code: '17' },
  { brand: 'Nipro', name: 'PES-170DS', code: '18' },
  { brand: 'Nipro', name: 'PES-190DS', code: '19' },
  { brand: 'Nipro', name: 'PES-210DS', code: '20' },
  { brand: 'Nipro', name: 'PES-110DH', code: '21' },
  { brand: 'Nipro', name: 'PES-130DH', code: '22' },
  { brand: 'Nipro', name: 'PES-150DH', code: '23' },
  { brand: 'Nipro', name: 'PES-170DH', code: '24' },
  { brand: 'Nipro', name: 'PES-190DH', code: '25' },
  { brand: 'Nipro', name: 'PES-210DH', code: '26' },
  { brand: 'Nipro', name: 'ELISIO-150H', code: '27' },
  { brand: 'Nipro', name: 'ELISIO-170H', code: '28' },
  { brand: 'Nipro', name: 'ELISIO-190H', code: '29' },
  { brand: 'Nipro', name: 'ELISIO-210H', code: '30' },
  { brand: 'Nipro', name: 'ELISIO-250H', code: '31' },
  { brand: 'Nipro', name: 'SUREFLUX-110G', code: '150' },
  { brand: 'Nipro', name: 'PUREFLUX-190H', code: '154' },
  { brand: 'Nipro', name: 'PUREFLUX-150H', code: '157' },
  { brand: 'Nipro', name: 'PUREFLUX-210H', code: '158' },
  { brand: 'Nipro', name: 'ELISIO-130H', code: '159' },
  { brand: 'Nipro', name: 'PUREFLUX-170H', code: '164' },
  { brand: 'Nipro', name: 'ELISIO-15H', code: '175' },
  { brand: 'Nipro', name: 'ELISIO-21H', code: '176' },
  { brand: 'Nipro', name: 'SUREFLUX-210UH', code: '177' },
  { brand: 'Nipro', name: 'SUREFLUX-250UH', code: '178' },
  { brand: 'Nipro', name: 'ELISIO-17H', code: '179' },
  { brand: 'Nipro', name: 'PES-1.6HF', code: '182' },
  { brand: 'Nipro', name: 'PES-2.0HF', code: '183' },
  { brand: 'Nipro', name: 'ELISIO-25H', code: '200' },
  { brand: 'Nipro', name: 'ELISIO-19H', code: '202' },
  { brand: 'Nipro', name: 'SUREFLUX-130G', code: '223' },
  { brand: 'Nipro', name: 'SUREFLUX-150G', code: '224' },
  { brand: 'Nipro', name: 'SUREFLUX-170G', code: '225' },
  { brand: 'Toray', name: 'B3-1.0A', code: '125' },
  { brand: 'Toray', name: 'B3-1.3A', code: '126' },
  { brand: 'Toray', name: 'B3-1.6A', code: '127' },
  { brand: 'Toray', name: 'B3-1.8A', code: '128' },
  { brand: 'Toray', name: 'B3-2.0A', code: '129' },
  { brand: 'Toray', name: 'B1-1.3H', code: '130' },
  { brand: 'Toray', name: 'B1-1.6H', code: '131' },
  { brand: 'Toray', name: 'B1-1.8H', code: '132' },
  { brand: 'Toray', name: 'B1-2.1H', code: '133' },
  { brand: 'Toray', name: 'BK-1.6U', code: '134' },
  { brand: 'Toray', name: 'BG-1.3U', code: '135' },
  { brand: 'Toray', name: 'BG-1.6U', code: '136' },
  { brand: 'Toray', name: 'BG-1.8U', code: '137' },
  { brand: 'Toray', name: 'BG-2.1U', code: '138' },
  { brand: 'Toray', name: 'BS-1.3', code: '139' },
  { brand: 'Toray', name: 'BS-1.6', code: '140' },
  { brand: 'Toray', name: 'BS-1.8', code: '141' },
  { brand: 'Toray', name: 'CS-1.3U', code: '142' },
  { brand: 'Toray', name: 'CS-1.6U', code: '143' },
  { brand: 'Toray', name: 'CS-1.8U', code: '144' },
  { brand: 'Toray', name: 'CS-2.1U', code: '145' },
  { brand: 'Toray', name: 'TS-1.3S', code: '146' },
  { brand: 'Toray', name: 'TS-1.6SL', code: '147' },
  { brand: 'Toray', name: 'TS-1.8SL', code: '148' },
  { brand: 'Toray', name: 'TS-2.1SL', code: '149' },
  { brand: 'Toray', name: 'BK-2.1U', code: '156' },
  { brand: 'Toray', name: 'TS-1.8SL', code: '160' },
  { brand: 'Toray', name: 'TS-2.1SL', code: '161' },
  { brand: 'Toray', name: 'PES-1.4HF', code: '194' },
  { brand: 'Toray', name: 'PES-1.6HF', code: '195' },
  { brand: 'Toray', name: 'PES-1.8HF', code: '196' },
  { brand: 'Toray', name: 'PES-2.2H', code: '201' },
  { brand: 'Toray', name: 'TS-1.8UL', code: '213' },
  { brand: 'Toray', name: 'TS-2.1UL', code: '214' },
  { brand: 'Toray', name: 'PES-2.0H', code: '219' },
  { brand: 'Toray', name: 'PES-2.5H', code: '220' },
  { brand: 'Toray', name: 'CS-1.6', code: '221' },
  { brand: 'Toray', name: 'CS-1.8', code: '222' },
  { brand: 'Nipro', name: 'SUREFLUX-130G', code: '223' },
  { brand: 'Nipro', name: 'SUREFLUX-150G', code: '224' },
  { brand: 'Nipro', name: 'SUREFLUX-170G', code: '225' },
  { brand: 'Hospitech', name: 'PES-1.4HF', code: '226' },
  { brand: 'Hospitech', name: 'PES-1.6HF', code: '227' },
  { brand: 'Hospitech', name: 'PES-1.8HF', code: '228' },
  { brand: 'Hospitech', name: 'PES-2.0HF', code: '229' },
  { brand: 'Hospitech', name: 'PES-2.2HF', code: '230' },
  { brand: 'Nipro', name: 'SUREFLUX-210G', code: '231' },
  { brand: 'Gambro', name: 'POLYFLUX-170H', code: '232' },
  { brand: 'Gambro', name: 'POLYFLUX-210H', code: '233' },
  { brand: 'Fresenius', name: 'Optiflux F16NR', code: '234' },
  { brand: 'Fresenius', name: 'Optiflux F18NR', code: '235' },
  { brand: 'Fresenius', name: 'Optiflux F20NR', code: '236' },
  { brand: 'B.Braun', name: 'Xevonta Hi23', code: '237' },
  { brand: 'Hospitech', name: 'PES-2.0MF', code: '238' },
  { brand: 'B.Braun', name: 'Xevonta Hi18', code: '239' },
  { brand: 'B.Braun', name: 'Xevonta Hi20', code: '240' },
  { brand: 'Fresenius', name: 'FX800', code: '241' },
  { brand: 'Fresenius', name: 'FX1000', code: '242' },
  { brand: 'Nipro', name: 'PUREFLUX-130H', code: '243' },
  { brand: 'Gambro', name: 'POLYFLUX-14L', code: '244' },
  { brand: 'Toray', name: 'PES-1.4MF', code: '245' },
  { brand: 'Toray', name: 'PES-1.8MF', code: '246' },
  { brand: 'Toray', name: 'PES-1.6MF', code: '247' },
  { brand: 'Fresenius', name: 'FX80 CorDiax', code: '248' },
  { brand: 'Fresenius', name: 'FX100 CorDiax', code: '249' },
  { brand: 'B.Braun', name: 'Xevonta Hi15', code: '251' },
  { brand: 'Baxter', name: 'XPM-130', code: '252' },
  { brand: 'Fresenius', name: 'FX60 CorDiax', code: '253' },
  { brand: 'Gambro', name: 'POLYFLUX-140H', code: '254' },
  { brand: 'Gambro', name: 'PES-2.0MF', code: '255' },
  { brand: 'Gambro', name: 'PES-2.2MF', code: '256' },
  { brand: 'Baxter', name: 'XPM-150', code: '257' },
  { brand: 'Baxter', name: 'XPM-110', code: '258' },
  { brand: 'Baxter', name: 'XPM-170', code: '259' },
  { brand: 'Asahi', name: 'FASFLO-PS-15H', code: '260' },
  { brand: 'Asahi', name: 'FASFLO-PS-18H', code: '261' },
  { brand: 'KAWASUMI', name: 'Renak PS-1.6W', code: '262' },
  { brand: 'KAWASUMI', name: 'Renak PS-1.9W', code: '263' },
  { brand: 'Fresenius', name: 'FX120', code: '264' },
  { brand: 'KAWASUMI', name: 'Renak PS-2.0W', code: '265' },
  { brand: 'KAWASUMI', name: 'Renak PS-2.3W', code: '266' },
  { brand: 'Baxter', name: 'Xenium XPM210', code: '267' },
  { brand: 'Baxter', name: 'Xenium XPM190', code: '268' },
  { brand: 'Nipro', name: 'ELISIO-13H', code: '269' },
  { brand: 'Gambro', name: 'POLYFLUX-17R', code: '270' },
  { brand: 'Nipro', name: 'ELISIO-15M', code: '271' },
  { brand: 'Nipro', name: 'ELISIO-13M', code: '272' },
  { brand: 'Toray', name: 'NV-21U', code: '273' },
  { brand: 'Toray', name: 'NV-18U', code: '274' },
  { brand: 'Toray', name: 'NV-15U', code: '275' },
  { brand: 'Fresenius', name: 'FX10', code: '276' },
  { brand: 'Toray', name: 'NV-13U', code: '277' },
  { brand: 'Fresenius', name: 'FX CorDiax 60', code: '278' },
  { brand: 'Fresenius', name: 'FX CorDiax 120', code: '279' },
  { brand: 'Fresenius', name: 'FX CorDiax 600', code: '280' },
  { brand: 'Fresenius', name: 'FX CorDiax 800', code: '281' },
  { brand: 'Fresenius', name: 'FX CorDiax 1000', code: '282' },
  { brand: 'Fresenius', name: 'FX 5', code: '283' },
  { brand: 'Fresenius', name: 'FX 8', code: '284' },
  { brand: 'Asahi', name: 'FASFLO-PS-21H', code: '285' },
  { brand: 'Gambro', name: 'SMARTFLUX HFP-150', code: '286' },
  { brand: 'Gambro', name: 'SMARTFLUX HFP-230', code: '287' },
  { brand: 'MEDICA', name: 'SMARTFLUX HFP-150', code: '288' },
  { brand: 'MEDICA', name: 'SMARTFLUX HFP-230', code: '289' },
  { brand: 'Nipro', name: 'ELISIO-17M', code: '290' },
  { brand: 'MEDICA', name: 'SMARTFLUX HFP-120', code: '291' },
  { brand: 'Nipro', name: 'ELISIO-21M', code: '292' },
  { brand: 'MEDICA', name: 'SMARTFLUX HFP-190', code: '293' },
  { brand: 'Gambro', name: 'Revaclear300', code: '294' },
  { brand: 'Gambro', name: 'Revaclear400', code: '295' },
  { brand: 'Nipro', name: 'ELISIO-11M', code: '296' },
  { brand: 'FIBERPURE', name: 'HF130', code: '297' },
  { brand: 'FIBERPURE', name: 'HF140', code: '298' },
  { brand: 'FIBERPURE', name: 'HF160', code: '299' },
  { brand: 'FIBERPURE', name: 'HF180', code: '300' },
  { brand: 'B.Braun', name: 'Diacap Pro 13H', code: '301' },
  { brand: 'B.Braun', name: 'Diacap Pro 16H', code: '302' },
  { brand: 'B.Braun', name: 'Diacap Pro 19H', code: '303' },
  { brand: 'BenQ', name: 'BenQ Qflux 14 LQ', code: '304' },
  { brand: 'BenQ', name: 'BenQ Qflux 16 LQ', code: '305' },
  { brand: 'BenQ', name: 'BenQ Qflux 18 LQ', code: '306' },
  { brand: 'BenQ', name: 'BenQ Qflux 20 LQ', code: '307' },
  { brand: 'BenQ', name: 'BenQ Qflux 22 LQ', code: '308' },
  { brand: 'BenQ', name: 'BenQ Qflux 15 HQ', code: '309' },
  { brand: 'BenQ', name: 'BenQ Qflux 17 HQ', code: '310' },
  { brand: 'BenQ', name: 'BenQ Qflux 19 HQ', code: '311' },
  { brand: 'BenQ', name: 'BenQ Qflux 21 HQ', code: '312' },
  { brand: 'BenQ', name: 'BenQ Qflux 23 HQ', code: '313' },
  { brand: 'Nipro', name: 'ELISIO-17K', code: '314' },
  { brand: 'Nipro', name: 'ELISIO-15K', code: '315' },
  { brand: 'Nipro', name: 'ELISIO-11K', code: '316' },
  { brand: 'Nipro', name: 'ELISIO-13K', code: '317' },
  { brand: 'Nipro', name: 'ELISIO-19K', code: '318' },
  { brand: 'Nipro', name: 'ELISIO-21K', code: '319' },
  { brand: 'B.Braun', name: 'Diacap Pro 13L', code: '320' },
  { brand: 'MEDICA', name: 'LFP-180', code: '321' },
  { brand: 'B.Braun', name: 'Diacap Pro 16L', code: '322' },
  { brand: 'B.Braun', name: 'Diacap Pro 19L', code: '323' },
  { brand: 'KAWASUMI', name: 'KF-15C', code: '324' },
  { brand: 'Hospitech', name: 'PES-2.2MF', code: '325' },
  { brand: 'Vital', name: 'Vital-V-14HF', code: '326' },
  { brand: 'Vital', name: 'Vital-V-16HF', code: '327' },
  { brand: 'Vital', name: 'Vital-V-18HF', code: '328' },
  { brand: 'Vital', name: 'Vital-V-20HF', code: '329' },
  { brand: 'Vital', name: 'Vital-V-22HF', code: '330' },
  { brand: 'Vital', name: 'Vital-V-24HF', code: '331' },
  { brand: 'Vital', name: 'Vital-V-14LF', code: '332' },
  { brand: 'Vital', name: 'Vital-V-16LF', code: '333' },
  { brand: 'Vital', name: 'Vital-V-18LF', code: '334' },
  { brand: 'Vital', name: 'Vital-V-20LF', code: '335' },
  { brand: 'Vital', name: 'Vital-V-22LF', code: '336' },
  { brand: 'Vital', name: 'Vital-V-24LF', code: '337' },
  { brand: 'Vital', name: 'Vital-DIA-13H', code: '338' },
  { brand: 'Vital', name: 'Vital-DIA-15H', code: '339' },
  { brand: 'Vital', name: 'Vital-DIA-17H', code: '340' },
  { brand: 'Vital', name: 'Vital-DIA-19H', code: '341' },
  { brand: 'Vital', name: 'Vital-DIA-21H', code: '342' },
  { brand: 'Vital', name: 'Vital-DIA-13L', code: '343' },
  { brand: 'Vital', name: 'Vital-DIA-15L', code: '344' },
  { brand: 'Vital', name: 'Vital-DIA-17L', code: '345' },
  { brand: 'Vital', name: 'Vital-DIA-19L', code: '346' },
  { brand: 'Vital', name: 'Vital-DIA-21L', code: '347' },
  { brand: 'Nipro', name: 'ELISIO-19M', code: '348' },
  { brand: 'Nipro', name: 'NIPRO-SUREFLUX-110UH', code: '349' },
  { brand: 'Nipro', name: 'NIPRO-SUREFLUX-130UH', code: '350' },
  { brand: 'Nipro', name: 'NIPRO-SUREFLUX-150UH', code: '351' },
  { brand: 'Nipro', name: 'NIPRO-SUREFLUX-170UH', code: '352' },
  { brand: 'Nipro', name: 'NIPRO-SUREFLUX-190UH', code: '353' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-110S', code: '354' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-130S', code: '355' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-150S', code: '356' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-170S', code: '357' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-190S', code: '358' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-210S', code: '359' },
  { brand: 'Nipro', name: 'NIPRO-FINEFLUX-250S', code: '360' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-09M', code: '361' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-11M', code: '362' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-13M', code: '363' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-15M', code: '364' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-17M', code: '365' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-19M', code: '366' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-21M', code: '367' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-11E', code: '368' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-13E', code: '369' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-15E', code: '370' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-17E', code: '371' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-19E', code: '372' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-21E', code: '373' },
  { brand: 'Nipro', name: 'NIPRO-MAXIFLUX-25E', code: '374' },
  { brand: 'Fresenius', name: 'FX-CorDiax 120', code: '375' },
  { brand: 'Allmed', name: 'Polypure H-10H', code: '376' },
  { brand: 'Allmed', name: 'Polypure H-13H', code: '377' },
  { brand: 'Allmed', name: 'Polypure H-14H', code: '378' },
  { brand: 'Allmed', name: 'Polypure H-16H', code: '379' },
  { brand: 'Allmed', name: 'Polypure H-18H', code: '380' },
  { brand: 'Allmed', name: 'Polypure H-20H', code: '381' },
  { brand: 'Allmed', name: 'Polypure H-22H', code: '382' },
  { brand: 'Allmed', name: 'Polypure M-10M', code: '383' },
  { brand: 'Allmed', name: 'Polypure M-13M', code: '384' },
  { brand: 'Allmed', name: 'Polypure M-14M', code: '385' },
  { brand: 'Allmed', name: 'Polypure M-16M', code: '386' },
  { brand: 'Allmed', name: 'Polypure M-18M', code: '387' },
  { brand: 'Allmed', name: 'Polypure M-20M', code: '388' },
  { brand: 'Allmed', name: 'Polypure M-22M', code: '389' },
  { brand: 'Allmed', name: 'Polypure 10', code: '390' },
  { brand: 'Allmed', name: 'Polypure 13', code: '391' },
  { brand: 'Allmed', name: 'Polypure 14', code: '392' },
  { brand: 'Allmed', name: 'Polypure 16', code: '393' },
  { brand: 'Allmed', name: 'Polypure 18', code: '394' },
  { brand: 'Allmed', name: 'Polypure 20', code: '395' },
  { brand: 'Allmed', name: 'Polypure 22', code: '396' },
  { brand: 'Baxter', name: 'Theranova-400', code: '397' },
];

/** 院內 AK 簡稱 → 官方對應代碼（2026-08 依現行醫囑值人工核對）
 *  ⚠️ 17UX/17HX＝Asahi APS-17UX/APS-17HX（2026-08-03 使用者確認），但官方對照表無 APS-17 系列
 *  （Asahi 只有 13/15/18/21 尺寸），暫以「廠牌-型號」文字帶入（同官方樣本檔 Nipro-ELISIO-15H 格式）；
 *  待與 KiDit 端確認代碼/文字後若需數字代碼，須請 KiDit 補建型號 */
export const HOSPITAL_AK_ALIASES: Record<string, string> = {
  'FX80': '91', // Fresenius FX80
  'Hi23': '237', // B.Braun Xevonta Hi23
  'BG-1.8U': '137', // Toray BG-1.8U
  '25H': '200', // Nipro ELISIO-25H
  'Pro-19H': '303', // B.Braun Diacap Pro 19H
  '21S': '58', // Asahi APS-21S
  '15S': '56', // Asahi APS-15S
  '17UX': 'Asahi-APS-17UX', // 官方表無此型號，暫帶文字
  '17HX': 'Asahi-APS-17HX', // 官方表無此型號，暫帶文字
  'CTA2000': '110', // KAWASUMI CTA-2000
  // '13M' 刻意不對應：官方表有 Nipro ELISIO-13M(272)/NIPRO-MAXIFLUX-13M(363)/Allmed Polypure M-13M(384) 三候選，待使用者確認
};

/** 依院內 AK 名稱解析官方代碼：先查簡稱別名，再精確比對官方名稱；查無回空字串 */
export function resolveAkCode(akName: string): string {
  const key = String(akName || '').trim();
  if (!key) return '';
  if (HOSPITAL_AK_ALIASES[key]) return HOSPITAL_AK_ALIASES[key];
  const exact = AK_DIALYZER_LIST.find((e) => e.name === key);
  return exact ? exact.code : '';
}
